declare namespace org {
    namespace bukkit {
        namespace loot {
            // @ts-ignore
            interface LootTable extends org.bukkit.Keyed {
                /**
                 * Returns a mutable list of loot generated by this LootTable.
                 */
                 populateLoot(random: any, context: org.bukkit.loot.LootContext): any[] /*java.util.Collection*/;
                /**
                 * Attempt to fill an inventory with this LootTable's loot.
                 */
                 fillInventory(inventory: org.bukkit.inventory.Inventory, random: any, context: org.bukkit.loot.LootContext): void;
            }
        }
    }
}
